DROP TABLE IF EXISTS POST_TAGS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS POST;

CREATE TABLE POSTS (
    no BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    views INT DEFAULT 0
);

DROP TABLE IF EXISTS POST_TAGS;

CREATE TABLE POST_TAGS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_no BIGINT NOT NULL,
    tag_name VARCHAR(50) NOT NULL,
    FOREIGN KEY (post_no) REFERENCES POSTS(no) ON DELETE CASCADE
);
